const DEFAULT_CHUNK_SIZE = Number(process.env.NEXT_PUBLIC_SEARCH_CHUNK_SIZE ?? '6');
const FALLBACK_CHUNK_SIZE = Number.isFinite(DEFAULT_CHUNK_SIZE) && DEFAULT_CHUNK_SIZE > 0 ? DEFAULT_CHUNK_SIZE : 6;

export const SEARCH_STREAM_CHUNK_SIZE = Math.min(Math.max(1, FALLBACK_CHUNK_SIZE), 10);
